% Generates an ECG waveform and accompanying heartbeat sound
%
% Contributors:
% Jasmine Le
%
% Documentation:
%   fs: Sampling frequency for the audio
%   dur: Duration of the audio (in seconds)
%   t: Time vector (in seconds)
%   ecg_waveform: Simulated ECG-like waveform
%   heartbeat_sound: Simulated heartbeat sound
%   combined_signal: Combined ECG waveform and heartbeat sound
%
% Description:
%   This function generates an ECG waveform and accompanying heartbeat
%   sound using sinusoidal components. It synthesizes the ECG waveform by
%   combining P wave, QRS complex, and T wave components generated by
%   'gen_ecg_waveform' function. The heartbeat sound is generated using a
%   simple sine wave with a decaying envelope to mimic the fading of the
%   heartbeat sound over time, created by the 'gen_heartbeat_sound'
%   function. The ECG waveform and heartbeat sound are then combined to
%   create a single signal. The combined signal is plotted, written to an
%   audio file, and played.
%
% Functions:
%   gen_ecg_waveform: Generates a simulated ECG-like waveform
%   gen_heartbeat_sound: Generates a simulated heartbeat sound
function heartbeat_sound = gen_heartbeat_sound(t, dur)
    % Generate heartbeat sound (a simple sine wave)
    f_heartbeat = 80; % Adjusting the frequency of the heartbeat sound
    heartbeat_sound = 0.5 * sin(2*pi*f_heartbeat*t); % Adjusting the amplitude of the heartbeat sound
            
    % Adding a decay to simulate the fading of the heartbeat sound
    decay_factor = exp(-t/4); % Adjust decay rate as needed
    heartbeat_sound = heartbeat_sound .* decay_factor;
            
    % Ensure the sound ends smoothly at the end of the duration
    heartbeat_sound(t > dur) = 0;
end